### PR TITLE
Add sign in prompt

### PR DESCRIPTION
**Pull request by BenElgar**
image

### CODE REVIEW

**Comment by BenElgar** [comment]
@jwmza do you reckon you could take a stab at styling this?

**Comment by brandonbloom** [comment]
screenshot or video? :)

**Comment by BenElgar** [comment]
There was one! I don't know what happened to it! One sec.

**Review by abergenw — COMMENTED** [review]
Few comments:
- Isn't prettier supposed to add brackets? That's what happens for me.
- Should the prompt be implemented as an iframe with react etc?
- Why use localStorage instead of the storage API we expose?

**Comment by BenElgar** [comment]
1. Ah, I understand the problem now. We don't set the relevant prettier setting or version and thus prettier will default to either adding or removing brackets depending on which version you have installed locally. I'll mandate a specific version in the package.json which should fix this.
2. Yes, done now. (I originally thought it would be a very simple box that would be trivial to style and not worth the overhead of another iframe but I now think that was dumb.)
3. I was trying to avoid adding the storage permission to the manifest since that will require users to manually approve updates to the extension. Now that it's been done anyway I'll swap to using the extension storage API.

**Comment by BenElgar** [comment]
Actually, on the localstorage front, I'm not clear on how to access the extension's storage API from within the context of a page handler in both a performant and secure manner. We could have the page handler post a request to the background script for the "isDismissed" state and then wait for a response but, given we're doing this at least once a second, that would seem to introduce a whole bunch of context switching for not much benefit. Unless you particularly object I'm not going to worry about it and keep using localstorage.

**Pull request merged**
